import {
  collection,
  doc,
  getDocs,
  query,
  runTransaction,
  serverTimestamp,
  updateDoc,
  where,
  writeBatch,
} from "firebase/firestore";
import { db } from "@/lib/firebase";
import { bumpCounters } from "@/lib/counters";
import { addXp, XP_REWARDS } from "@/lib/gamification";
import { dayKey, parseDayKey } from "@/lib/dates";
import { computeEndDate } from "@/lib/sprints";
import type { ErrorBookDoc, ErrorStatus, ErrorType } from "@/lib/schema";

export interface NewErrorInput {
  subjectId: string;
  subjectName: string;
  chapterId?: string;
  chapterName?: string;
  mockTestId?: string;
  errorType: ErrorType;
  questionText?: string;
  whyWrong: string;
  reviewDate: string;
}

export async function createError(uid: string, input: NewErrorInput): Promise<void> {
  const ref = doc(collection(db, "users", uid, "errors"));
  const errorDoc: Omit<ErrorBookDoc, "createdAt"> = {
    subjectId: input.subjectId,
    subjectName: input.subjectName,
    chapterId: input.chapterId,
    chapterName: input.chapterName,
    mockTestId: input.mockTestId,
    errorType: input.errorType,
    questionText: input.questionText,
    whyWrong: input.whyWrong,
    reviewDate: input.reviewDate,
    status: "open",
  };
  await writeBatch(db)
    .set(ref, { ...errorDoc, createdAt: serverTimestamp() })
    .commit();
}

export async function setErrorStatus(
  uid: string,
  errorId: string,
  status: ErrorStatus
): Promise<void> {
  await updateDoc(doc(db, "users", uid, "errors", errorId), { status });
}

/**
 * Marks an open mistake as reviewed from the Today Review hub and counts it as
 * a revision for the day (revision counters, XP) — one write-path, no UI sync
 * needed. The mistake itself stays in the log with status "reviewed".
 */
export async function completeMistakeReview(
  uid: string,
  errorId: string,
  when: Date = new Date()
): Promise<void> {
  const batch = writeBatch(db);
  batch.update(doc(db, "users", uid, "errors", errorId), { status: "reviewed" });
  bumpCounters(batch, uid, parseDayKey(dayKey(when)), { revisionsDone: 1 });
  addXp(batch, uid, XP_REWARDS.taskComplete);
  await batch.commit();
}

export async function deleteError(uid: string, errorId: string): Promise<void> {
  await writeBatch(db).delete(doc(db, "users", uid, "errors", errorId)).commit();
}

/**
 * Groups every open mistake by chapter and spins up a 7-day "Mistakes
 * Revision Sprint": one revision task per chapter (so a chapter with many
 * repeated mistakes gets one focused re-do, not N duplicate tasks), then
 * marks those errors "reviewed" so re-running this doesn't duplicate work.
 * Returns the new sprint id, or null if there were no open mistakes.
 *
 * Open errors are fetched first, then re-verified as still "open" *inside*
 * the transaction, so concurrent tabs can't both generate a duplicate sprint.
 */
export async function generateMistakesSprint(uid: string): Promise<string | null> {
  const candidates = await getDocs(
    query(collection(db, "users", uid, "errors"), where("status", "==", "open"))
  );
  if (candidates.empty) return null;

  return runTransaction(db, async (tx) => {
    const openErrors: (ErrorBookDoc & { id: string })[] = [];
    for (const d of candidates.docs) {
      const snap = await tx.get(d.ref);
      const err = snap.data() as ErrorBookDoc | undefined;
      if (err && err.status === "open") openErrors.push({ id: d.id, ...err });
    }
    if (openErrors.length === 0) return null;

    const byChapter = new Map<string, typeof openErrors>();
    for (const err of openErrors) {
      const key = err.chapterId ?? `subject:${err.subjectId}`;
      byChapter.set(key, [...(byChapter.get(key) ?? []), err]);
    }

    const startDate = dayKey(new Date());
    const sprintRef = doc(collection(db, "users", uid, "sprints"));

    tx.set(sprintRef, {
      name: "Mistakes Revision Sprint",
      type: "mistake",
      startDate,
      endDate: computeEndDate(startDate, "mistake"),
      goals: {
        targetQuestions: openErrors.length * 2,
        targetPyqs: 0,
        targetMocks: 0,
        targetFocusHours: Math.max(1, Math.ceil(openErrors.length / 4)),
      },
      progress: { questions: 0, pyqs: 0, mocks: 0, focusMinutes: 0 },
      status: "active",
      autoGenerated: true,
      createdAt: serverTimestamp(),
    });

    for (const [, group] of byChapter) {
      const first = group[0];
      const taskRef = doc(collection(db, "users", uid, "tasks"));
      tx.set(taskRef, {
        title: `Redo ${group.length} mistake${group.length > 1 ? "s" : ""} — ${
          first.chapterName ?? first.subjectName
        }`,
        category: "revision",
        subjectId: first.subjectId,
        subjectName: first.subjectName,
        chapterId: first.chapterId,
        chapterName: first.chapterName,
        priority: "high",
        difficulty: "med",
        estimatedMinutes: group.length * 10,
        targetQuestions: group.length,
        scheduledDate: startDate,
        sprintId: sprintRef.id,
        status: "todo",
        actualMinutes: 0,
        questionsDone: 0,
        source: "mistakeSprint",
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });
      bumpCounters(tx, uid, parseDayKey(startDate), { plannedTasks: 1 });
    }

    for (const err of openErrors) {
      tx.update(doc(db, "users", uid, "errors", err.id), { status: "reviewed" });
    }

    return sprintRef.id;
  });
}
