import { describe, expect, it } from "vitest";
import { computeSprintRetro } from "@/lib/retro";
import { emptyCounter, type FocusSessionDoc, type SprintDoc } from "@/lib/schema";

function makeSprint(overrides: Partial<SprintDoc> = {}): SprintDoc {
  return {
    name: "revise physics",
    type: "7",
    startDate: "2026-08-10",
    endDate: "2026-08-16",
    goals: { targetQuestions: 100, targetPyqs: 10, targetMocks: 0, targetFocusHours: 10 },
    progress: { questions: 60, pyqs: 10, mocks: 0, focusMinutes: 420 },
    status: "completed",
    autoGenerated: false,
    createdAt: { toDate: () => new Date() } as unknown as SprintDoc["createdAt"],
    ...overrides,
  };
}

function dayCounter(id: string, focusMinutes: number, questionsDone = 0) {
  return { id, data: { ...emptyCounter(), focusMinutes, questionsDone } };
}

function session(date: string, subjectName: string, focusMinutes: number): FocusSessionDoc {
  return {
    subjectName,
    focusMinutes,
    date,
    plannedMinutes: focusMinutes,
    mode: "25/5",
    questionsDone: 0,
    startedAt: { toDate: () => new Date() } as unknown as FocusSessionDoc["startedAt"],
    completed: true,
  };
}

describe("computeSprintRetro", () => {
  it("marks goals achieved only when progress meets the target", () => {
    const retro = computeSprintRetro(makeSprint(), [], []);
    expect(retro.goals.find((g) => g.title === "Questions")).toMatchObject({
      done: 60,
      target: 100,
      achieved: false,
    });
    expect(retro.goals.find((g) => g.title === "PYQs")).toMatchObject({
      achieved: true,
    });
  });

  it("counts only goals with a non-zero target", () => {
    const sprint = makeSprint({ goals: { targetQuestions: 100, targetPyqs: 10, targetMocks: 0, targetFocusHours: 10 } });
    const retro = computeSprintRetro(sprint, [], []);
    expect(retro.goalCount).toBe(3); // mocks target is 0 → excluded
    expect(retro.goalsAchieved).toBe(1); // only PYQs (60/100 questions, 420/600 focus min)
  });

  it("derives best/worst days from the counters in the window only", () => {
    const counters = [
      dayCounter("day_2026-08-10", 60),
      dayCounter("day_2026-08-11", 120),
      dayCounter("day_2026-08-12", 0), // outside focus but inside window (0)
      dayCounter("day_2026-08-20", 999), // outside window — must be ignored
    ];
    const retro = computeSprintRetro(makeSprint(), counters, []);
    expect(retro.bestDay).toMatchObject({ minutes: 120 });
    expect(retro.bestDay?.date).toBe("2026-08-11");
    expect(retro.worstDay?.minutes).toBe(60); // 08-12 is 0 min (excluded); 60 is the lower non-zero day
    expect(retro.focusTotalMin).toBe(180);
  });

  it("builds subject mix from sessions in the window", () => {
    const sessions = [
      session("2026-08-10", "Physics", 60),
      session("2026-08-11", "Physics", 60),
      session("2026-08-15", "Maths", 60),
      session("2026-08-30", "Outsider", 999), // outside window — ignored
    ];
    const retro = computeSprintRetro(makeSprint(), [], sessions);
    expect(retro.subjectFocus[0]).toMatchObject({ name: "Physics", minutes: 120, pct: 67 });
    expect(retro.subjectFocus).toHaveLength(2);
  });

  it("celebrates a sprint that hit every goal", () => {
    const sprint = makeSprint({
      goals: { targetQuestions: 100, targetPyqs: 10, targetMocks: 0, targetFocusHours: 7 },
      progress: { questions: 100, pyqs: 10, mocks: 0, focusMinutes: 420 },
    });
    const retro = computeSprintRetro(sprint, [], []);
    expect(retro.congrats).toContain("Sprint complete");
    expect(retro.strengths.some((s) => s.toLowerCase().includes("every sprint goal"))).toBe(true);
  });

  it("nudges lighter targets after a low-completion finish", () => {
    const sprint = makeSprint({ progress: { questions: 5, pyqs: 0, mocks: 0, focusMinutes: 60 } });
    const retro = computeSprintRetro(sprint, [], []);
    expect(retro.completionPct).toBeLessThan(90);
    expect(retro.suggestions.some((s) => s.includes("lighter"))).toBe(true);
  });

  it("acknowledges an abandoned sprint and suggests a lighter restart", () => {
    const sprint = makeSprint({ status: "abandoned" });
    const retro = computeSprintRetro(sprint, [], []);
    expect(retro.status).toBe("abandoned");
    expect(retro.weaknesses.some((w) => w.includes("ended early"))).toBe(true);
    expect(retro.suggestions.some((s) => s.includes("lighter"))).toBe(true);
  });
});