import { collection, doc, increment, runTransaction, serverTimestamp, setDoc, updateDoc } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { addDays, dayKey, parseDayKey } from "@/lib/dates";
import { XP_REWARDS } from "@/lib/gamification";
import type { SprintDoc, SprintType } from "@/lib/schema";

export const SPRINT_LENGTH_DAYS: Record<SprintType, number> = {
  "7": 7,
  "14": 14,
  "30": 30,
  mistake: 7,
};

export interface NewSprintInput {
  name: string;
  type: SprintType;
  startDate: string; // YYYY-MM-DD
  goals: SprintDoc["goals"];
}

export function computeEndDate(startDate: string, type: SprintType): string {
  return dayKey(addDays(parseDayKey(startDate), SPRINT_LENGTH_DAYS[type] - 1));
}

export async function createSprint(uid: string, input: NewSprintInput): Promise<string> {
  const ref = doc(collection(db, "users", uid, "sprints"));
  const sprint: Omit<SprintDoc, "createdAt"> & { createdAt: unknown } = {
    name: input.name,
    type: input.type,
    startDate: input.startDate,
    endDate: computeEndDate(input.startDate, input.type),
    goals: input.goals,
    progress: { questions: 0, pyqs: 0, mocks: 0, focusMinutes: 0 },
    status: "active",
    autoGenerated: false,
    createdAt: serverTimestamp(),
  };
  await setDoc(ref, sprint);
  return ref.id;
}

export async function setSprintStatus(
  uid: string,
  sprintId: string,
  status: SprintDoc["status"]
): Promise<void> {
  if (status !== "completed") {
    await updateDoc(doc(db, "users", uid, "sprints", sprintId), { status });
    return;
  }
  // Completing (vs abandoning) is the only sprint transition worth XP for —
  // done in a transaction so the status flip and the +100 XP land together
  // and concurrent devices can't double-award (transaction re-reads the
  // sprint, so a second "complete" sees it updated and skips the reward).
  await runTransaction(db, async (tx) => {
    const ref = doc(db, "users", uid, "sprints", sprintId);
    const snap = await tx.get(ref);
    if (!snap.exists() || snap.data().status === "completed") return;
    tx.update(ref, { status });
    tx.set(doc(db, "users", uid), { xp: increment(XP_REWARDS.sprintCompleted) }, { merge: true });
  });
}

/** Which day of the sprint "today" falls on (1-indexed), and overall length. */
export function sprintDayProgress(sprint: SprintDoc, today: Date = new Date()) {
  const totalDays = SPRINT_LENGTH_DAYS[sprint.type];
  // Calendar-day difference between two YYYY-MM-DD keys via UTC math, so it's
  // independent of the runner's timezone (mixing local-midnight Dates with
  // parseDayKey's UTC-midnight instant caused an off-by-one in TZs east of UTC).
  const [y1, m1, d1] = sprint.startDate.split("-").map(Number);
  const todayKey = dayKey(today);
  const [y2, m2, d2] = todayKey.split("-").map(Number);
  const elapsedDays = Math.round(
    (Date.UTC(y2, m2 - 1, d2) - Date.UTC(y1, m1 - 1, d1)) / 86400000
  ) + 1;
  const currentDay = Math.min(Math.max(elapsedDays, 1), totalDays);
  return { currentDay, totalDays };
}

export function sprintCompletionPct(sprint: SprintDoc): number {
  // Average of each goal's capped completion ratio (ignoring zero-target goals),
  // matching how the sprint detail ring and retrofit compute it.
  const ratios = [
    [sprint.progress.questions, sprint.goals.targetQuestions],
    [sprint.progress.pyqs, sprint.goals.targetPyqs],
    [sprint.progress.mocks, sprint.goals.targetMocks],
    [sprint.progress.focusMinutes, sprint.goals.targetFocusHours * 60],
  ].filter(([, target]) => target > 0);
  if (ratios.length === 0) return 0;
  const avg =
    ratios.reduce((sum, [done, target]) => sum + Math.min(1, done / target), 0) / ratios.length;
  return Math.round(avg * 100);
}
