import { describe, expect, it } from "vitest";
import {
  computeEndDate,
  sprintCompletionPct,
  sprintDayProgress,
  SPRINT_LENGTH_DAYS,
} from "@/lib/sprints";
import type { SprintDoc } from "@/lib/schema";

function makeSprint(overrides: Partial<SprintDoc> = {}): SprintDoc {
  return {
    name: "test sprint",
    type: "7",
    startDate: "2026-08-10",
    endDate: "2026-08-16",
    goals: { targetQuestions: 100, targetPyqs: 10, targetMocks: 1, targetFocusHours: 10 },
    progress: { questions: 0, pyqs: 0, mocks: 0, focusMinutes: 0 },
    status: "active",
    autoGenerated: false,
    createdAt: { toDate: () => new Date() } as unknown as SprintDoc["createdAt"],
    ...overrides,
  };
}

describe("SPRINT_LENGTH_DAYS", () => {
  it("maps each sprint type to its day length", () => {
    expect(SPRINT_LENGTH_DAYS).toEqual({ "7": 7, "14": 14, "30": 30, mistake: 7 });
  });
});

describe("computeEndDate", () => {
  it("7-day sprint ends 6 days after start (inclusive)", () => {
    expect(computeEndDate("2026-08-10", "7")).toBe("2026-08-16");
  });

  it("14 and 30 day sprints end correctly", () => {
    expect(computeEndDate("2026-08-10", "14")).toBe("2026-08-23");
    expect(computeEndDate("2026-08-10", "30")).toBe("2026-09-08");
  });
});

describe("sprintDayProgress", () => {
  it("counts days inclusively from the start date", () => {
    const sprint = makeSprint();
    expect(
      sprintDayProgress(sprint, new Date(2026, 7, 10)).currentDay
    ).toBe(1);
    expect(
      sprintDayProgress(sprint, new Date(2026, 7, 13)).currentDay
    ).toBe(4);
  });

  it("clamps before start to 1 and after end to totalDays", () => {
    const sprint = makeSprint();
    expect(sprintDayProgress(sprint, new Date(2026, 7, 1)).currentDay).toBe(1);
    expect(sprintDayProgress(sprint, new Date(2026, 8, 1)).currentDay).toBe(7);
  });
});

describe("sprintCompletionPct", () => {
  it("returns 0 with no progress", () => {
    expect(sprintCompletionPct(makeSprint())).toBe(0);
  });

  it("computes the weighted proportion across all goals", () => {
    const sprint = makeSprint({
      goals: { targetQuestions: 100, targetPyqs: 10, targetMocks: 1, targetFocusHours: 10 },
      progress: { questions: 50, pyqs: 10, mocks: 0, focusMinutes: 300 },
    });
    // fraction = (50/100 + 10/10 + 0/1 + 300/600) / 4 = (0.5 + 1 + 0 + 0.5)/4 = 0.5
    expect(sprintCompletionPct(sprint)).toBe(50);
  });

  it("caps over-achievement at 100%", () => {
    const sprint = makeSprint({
      progress: { questions: 500, pyqs: 20, mocks: 5, focusMinutes: 9999 },
    });
    expect(sprintCompletionPct(sprint)).toBe(100);
  });
});